### ISSUE TITLE
2 Background songs playing

### ISSUE THREAD

**Issue by alanfermtz** [sircharlo/mmm-refactor#128]
If you setup the app in the the day of your meeting, at the end of the setup it will play 2 background songs at the same time, and if you stop it, it will still playing the one left with no option to stop.

24.7.3 x64
windows

**Comment by ux-git** [comment]
In our Kingdom Hall we have exactly the same issue but with JW Library playing either two songs simultaneously or stopping the playback after two songs played 😀 Just fun fact.

**Comment by sircharlo** [comment]
> In our Kingdom Hall we have exactly the same issue but with JW Library playing either two songs simultaneously or stopping the playback after two songs played 😀 Just fun fact.

I've never heard of this bug but it sounds great haha
