### ISSUE TITLE
Audio playback conflict

### ISSUE THREAD

**Issue by ux-git** [sircharlo/mmm-refactor#132]
On the latest version, starting a video playback while the background music is playing, causes them both to play simultaneously.

I suppose the background music should be automatically stopped once a video from the media list has been played, because it's most likely an opening song. Plus, M³ doesn't support the countdown scenario anymore, so I can't think of a real use-case for playing both video and background audio simultaneously.

What do you think?

**Comment by sircharlo** [comment]
My thoughts were that it's quite possible that the AV operator is testing media playback before the meeting to make sure all is well. In that case there is no reason to stop the music, as he's probably just playing a few seconds here and there.

**Comment by ux-git** [comment]
How about temporarily pausing the audio playback while the video is playing and then automatically resuming it once the video stops? This approach will (1) prioritize the video when needed, and (2) prevent audio overlap, which is generally undesirable in any case I guess. Resulting in a better user experience without sacrificing any realistic use cases.

**Comment by sircharlo** [comment]
I like it. For simplicity, I've made the audio inaudible rather than pause it, but I've implemented the general logic you describe in https://github.com/sircharlo/mmm-refactor/commit/4d0c7b4b8a84cf3ec4910fd6680713a88a980b84.

**Comment by ux-git** [comment]
Awesome solution
