### ISSUE TITLE
Polished app icon (macOS and Windows)

### ISSUE THREAD

**Issue by ux-git** [sircharlo/mmm-refactor#19]
Hey! I'm excited about the v2 release, perhaps as much as you 😀 

I've created the icon that aligns with the macOS guidelines and makes the icon correct size, and I'd say more eye-catchy (a bit more contrast, a tiny bit of shadows, etc). If you think this icon works fine for the Windows version as well, we can use it. If you would like to somehow tweak it more, let me know.

**Comparison example:**
<img width="543" alt="Screenshot 2024-06-23 at 10 46 23" src="https://github.com/sircharlo/mmm-refactor/assets/80993061/16449e99-2806-4d06-bcc2-3b7c72d3d77c">
<img width="543" alt="Screenshot 2024-06-23 at 11 13 06" src="https://github.com/sircharlo/mmm-refactor/assets/80993061/0fed8f07-7738-4bbf-a53f-d28f19ef19f3">

**Files include:**
• .icns file for Mac;
• .ico file for Windows;
• PNG with no paddings that can be used as a logo.

**Download:**
[m3-icons.zip](https://github.com/user-attachments/files/15943967/m3-icons.zip)

**Comment by sircharlo** [comment]
This looks amazing!!!
I've implemented it, it'll be released shortly in the next alpha build 😄 
Thank you so much!

**Comment by sircharlo** [comment]
Released!

**Comment by ux-git** [comment]
@sircharlo my pleasure! The new version is so much easier to use. New approach is definitely miles ahead! 🙌 Great work! 

There is some room for UI improvements, to make the app even more intuitive and easier to use. But it's just about style consistency, I'll take a deeper look and provide you some feedback and suggestions, since I believe current stage is the best time for UI/UX improvements.

**Comment by sircharlo** [comment]
> @sircharlo my pleasure! The new version is so much easier to use. New approach is definitely miles ahead! 🙌 Great work! 

Thank you! That was definitely the goal.


> There is some room for UI improvements, to make the app even more intuitive and easier to use. But it's just about style consistency, I'll take a deeper look and provide you some feedback and suggestions, since I believe current stage is the best time for UI/UX improvements.

Absolutely! Let me know if you'd like to collaborate in any way; I'll accept any help offered 😄

**Comment by ux-git** [comment]
@sircharlo the icon on macOS should be smaller. The icon size is indeed 1024x1024px, but the icon area is only 832x832. Using these sizes, we get the icon that is the same size as others.

<img width="578" alt="Screenshot 2024-06-24 at 19 27 31" src="https://github.com/sircharlo/mmm-refactor/assets/80993061/de5c7a2b-87bc-488a-83c7-3e0178dd3d8d">

**Comment by ux-git** [comment]
The same situation is in the apps list:

<img width="578" alt="Screenshot 2024-06-24 at 19 31 09" src="https://github.com/sircharlo/mmm-refactor/assets/80993061/22977caa-ad16-45e2-86a2-72094d808d6b">

**Comment by sircharlo** [comment]
This app should stand out! Just kidding.
I used Quasar's icon remuxer; I'll just go in and manually tweak the generated icons for tonight's release.
Thanks for the heads up.

**Comment by ux-git** [comment]
Have you used the PNG image by any chance? The PNG one among others is to be used as a logo for GitHub, website, etc etc, not as an app icon. This PNG version has no padding and no required icon shadow. 

The other two files with proper icon formats were intended for macOS and Windows use. Just double checking.

**Comment by sircharlo** [comment]
> @sircharlo Have you used the PNG image by any chance? The PNG one among others is to be used as a logo for GitHub, website, etc etc, not as an app icon. This PNG version has no padding and no required icon shadow.
> 
> The other two files with proper icon formats were intended for macOS and Windows use. Just double checking.

I very much used the PNG; that's the format that IconGenie supports so I just ran with it. Thanks for pointing that out. I've updated the app icons to use the correct version in 24.6.5, which should be released within 30 minutes.

**Comment by ux-git** [comment]
Got it. Then, just in case when needed, I can send you a PNG version of the app icon once needed, just ping me.

**Comment by sircharlo** [comment]
> Got it. Then, just in case when needed, I can send you a PNG version of the app icon once needed, just ping me.

Thanks! Send it my way; I converted the ICO to a PNG, but it's not the best. Also, I think the design specs for Windows are different? I used the icon you initially sent, and the icon is way too small in the Windows taskbar.

**Comment by ux-git** [comment]
There you go: [M3-icons-and-logo.zip](https://github.com/user-attachments/files/15965712/M3-icons-and-logo.zip)

**Comment by sircharlo** [comment]
Thank you!
