### ISSUE TITLE
Bug: Setup Wizard -> Yeartext -> Back

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/mmm-refactor#206]
Hi!

I'm just playing around with this new version and stumbled upon a bug...

I followed the initial configuration setup wizard, all the way to the yeartext step where it says: "you'll notice the yeartext is showing now". When I press the back button from that point, I get stuck. The "Almost done!" step isn't being opened as I would expect. Instead I'm in a sort of limbo between the two steps.

Workaround: Delete the new, incomplete congregation and start over.

![Schermafbeelding 2024-09-17 132813](https://github.com/user-attachments/assets/2dd52e94-d643-4107-bfe0-f115b97ea78f)

**Comment by sircharlo** [comment]
He's back! 😄 
Thanks for this. Fixed in https://github.com/sircharlo/mmm-refactor/commit/c31121a075d153976b9946bb4c1e318c267d7700.
