### ISSUE TITLE
Bug: Play background music in language other than English

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/mmm-refactor#207]
When trying to play the background music in a language other than English, it seems to get stuck on some error. It just keeps freezing. I can't open the console in production to provide more details. When I reopen and switch to English, it works again.

![music](https://github.com/user-attachments/assets/174935c7-ae5b-43dc-9416-d7e9ebee78c3)

**Comment by sircharlo** [comment]
Hm. Interesting glitch, caused by at least two separate issues. Should work fine as of https://github.com/sircharlo/mmm-refactor/commit/01b79ba24e423b92314fc643263a80eb0457ff9d.
