### ISSUE TITLE
Bug: reset order to original media sections

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/mmm-refactor#208]
When dragging media items outside of their original section (treasures, apply yourselves, imported, etc) and then resetting the order. The items are ordered within their current section, but they are not returned to their original section. 

For example, when dragging the opening song to the bottom of the Apply yourself section and resetting the order, the song is placed at the top of the Apply yourself section.

![sorting](https://github.com/user-attachments/assets/7d5174ca-c491-475c-9d8a-43248f4d949d)

**Comment by sircharlo** [comment]
This is on my list of things to eventually improve.

**Comment by sircharlo** [comment]
Fixed in https://github.com/sircharlo/mmm-refactor/commit/9b7a8b5c8d6d51d01e926c389fa01e2a948877a1!
Note that this fix won't work for meetings that have already been cached.
