### ISSUE TITLE
Feature Request: show video custom start end range

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/mmm-refactor#209]
It would be nice to see the custom range start and end in the slider, by giving it another color (like the old M3). Don't know if the quasar components support that...

![range](https://github.com/user-attachments/assets/d19496dc-cd5b-4bf5-8dad-3f3db64333de)

**Comment by mtdvlpr** [comment]
See https://quasar.dev/vue-components/slider/#example--color-customizations

**Comment by sircharlo** [comment]
It is there but very faded. Maybe I'll try to put a more visible color for the disabled bits.

**Comment by sircharlo** [comment]
Trying something out in https://github.com/sircharlo/mmm-refactor/commit/6f5e7475311829b610af7ce7a34ee96f2575d027.

**Comment by mtdvlpr** [comment]
Looks great to me!
