### ISSUE TITLE
M³ test version for parallel installation

### ISSUE THREAD

**Issue by mrtavor** [sircharlo/mmm-refactor#99]
Is it possible to create a version of the program that will be installed as a second M3 program on a computer without replacing the existing program? It would be nice to have such a version to test the new interface in the Kingdom Hall and not have problems with the main M3 program that is currently in use.

**Comment by mrtavor** [comment]
Hey @sircharlo I found a way to install two versions of the M3 program but faced issues. With version 24.7.1 already installed, I added version 24.4.1, but each installation updated the same folder, so only the latest version ran.

To fix this, I copied the 24.4.1 folder before installing 24.7.1, allowing both versions to coexist.

If there's an easier way to install two versions without them replacing each other, I would appreciate your advice.

**Comment by sircharlo** [comment]
> Hey @sircharlo I found a way to install two versions of the M3 program but faced issues. With version 24.7.1 already installed, I added version 24.4.1, but each installation updated the same folder, so only the latest version ran.
> 
> To fix this, I copied the 24.4.1 folder before installing 24.7.1, allowing both versions to coexist.
> 
> If there's an easier way to install two versions without them replacing each other, I would appreciate your advice.

Even though the update the same folder, the settings are stored differently for both versions. Does that still cause a conflict in your case? I’ve been using both versions alternatively with no issues.

**Comment by mrtavor** [comment]
It sounds good, and it's happening to me the same way (without any errors). Can you explain how you run the two programs? I have only one icon for the program and I don't quite understand how to launch two different versions through it.
